// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Domain.Entities.Goal", b =>
                {
                    b.Property<int>("GoalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GoalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoalTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("TEXT");

                    b.HasKey("GoalID");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Domain.Entities.Note", b =>
                {
                    b.Property<int>("NoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubjectID")
                        .HasColumnType("INTEGER");

                    b.HasKey("NoteID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Domain.Entities.Schedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ScheduleID");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Domain.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubjectID");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectID = 1,
                            Description = "Math subject",
                            Progress = 50,
                            SubjectName = "Mathematics",
                            TargetHours = 40
                        },
                        new
                        {
                            SubjectID = 2,
                            Description = "C# Programming",
                            Progress = 30,
                            SubjectName = "Programming",
                            TargetHours = 60
                        },
                        new
                        {
                            SubjectID = 3,
                            Description = "Physics course",
                            Progress = 70,
                            SubjectName = "Physics",
                            TargetHours = 50
                        },
                        new
                        {
                            SubjectID = 4,
                            Description = "Chemistry course",
                            Progress = 40,
                            SubjectName = "Chemistry",
                            TargetHours = 50
                        },
                        new
                        {
                            SubjectID = 5,
                            Description = "History subject",
                            Progress = 60,
                            SubjectName = "History",
                            TargetHours = 50
                        },
                        new
                        {
                            SubjectID = 6,
                            Description = "English",
                            Progress = 80,
                            SubjectName = "Language",
                            TargetHours = 50
                        });
                });

            modelBuilder.Entity("Domain.Entities.Note", b =>
                {
                    b.HasOne("Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectID");

                    b.Navigation("Subject");
                });
#pragma warning restore 612, 618
        }
    }
}
